Repository oasis-tcs/csaf, pull requests merged in 2022-09, with the labels that each got.

#582 Committee Specification 03
  csaf_2.0/prose/csaf-v2-editor-draft.md
Labels: editorial, oasis_tc_process

#585 Organizing meeting minutes in folders per year
  meeting_minutes/2021/2021-09-29.md
  meeting_minutes/2021/2021-10-27.md
  meeting_minutes/2021/2021-11-24.md
  meeting_minutes/2022/2022-01-26.md
  meeting_minutes/2022/2022-02-23.md
  meeting_minutes/2022/2022-03-30.md
  meeting_minutes/2022/2022-04-27.md
  meeting_minutes/2022/2022-05-18.md
  meeting_minutes/2022/2022-06-29.md
  meeting_minutes/2022/2022-07-20.md
  meeting_minutes/2022/2022-08-31.md
Labels: documentation

#587 Proposed three registration content forms for upstreams
  csaf_2.0/register/dot-well-dash-known-slash/csaf-aggregator.txt
  csaf_2.0/register/dot-well-dash-known-slash/csaf.txt
  csaf_2.0/register/security-dot-txt/csaf.txt
Labels: oasis_tc_process
