Repository oasis-tcs/csaf, pull requests merged in 2022-02, with the labels that each got.

#402 CSAF mapping table
  notes/whats-new-csaf-v2.0-cn01.md
Labels: csaf 2.0, editorial, committee note

#403 Replace PGP with OpenPGP
  csaf_2.0/prose/csaf-v2-editor-draft.md
Labels: CS02

#404 Public openpgp key
  csaf_2.0/examples/provider-metadata/example-01-provider-metadata.json
  csaf_2.0/json_schema/provider_json_schema.json
  csaf_2.0/prose/csaf-v2-editor-draft.md
Labels: CS02

#412 Private languages
  csaf_2.0/prose/csaf-v2-editor-draft.md
  csaf_2.0/test/validator/data/optional/OASIS_CSAF_TC-CSAF_2_0-2021-6-2-14-01.json
  csaf_2.0/test/validator/data/optional/OASIS_CSAF_TC-CSAF_2_0-2021-6-2-15-01.json
Labels: CS02

#411 Source language
  csaf_2.0/prose/csaf-v2-editor-draft.md
  csaf_2.0/test/validator/data/mandatory/OASIS_CSAF_TC-CSAF_2_0-2021-6-1-28-01.json
Labels: CS02

#409 Generic profile
  csaf_2.0/prose/csaf-v2-editor-draft.md
Labels: bug, CS02

#417 Serial numbers
  csaf_2.0/json_schema/csaf_json_schema.json
  csaf_2.0/prose/csaf-v2-editor-draft.md
Labels: CS02

#415 Model numbers
  csaf_2.0/json_schema/csaf_json_schema.json
  csaf_2.0/prose/csaf-v2-editor-draft.md
Labels: CS02

#405 Support for multiple ids in vulnerabilities
  csaf_2.0/examples/csaf/CVE-2018-0171-modified.json
  csaf_2.0/json_schema/csaf_json_schema.json
  csaf_2.0/prose/csaf-v2-editor-draft.md
  notes/whats-new-csaf-v2.0-cn01.md
Labels: CS02

#414 Product identification helper test
  csaf_2.0/prose/csaf-v2-editor-draft.md
  csaf_2.0/test/validator/data/optional/OASIS_CSAF_TC-CSAF_2_0-2021-6-2-16-01.json
Labels: CS02

#420 CVE in IDs
  csaf_2.0/prose/csaf-v2-editor-draft.md
  csaf_2.0/test/validator/data/optional/OASIS_CSAF_TC-CSAF_2_0-2021-6-2-17-01.json
Labels: CS02

#422 Product tree guidance
  csaf_2.0/prose/csaf-v2-editor-draft.md
  csaf_2.0/test/validator/data/informative/OASIS_CSAF_TC-CSAF_2_0-2021-6-3-09-01.json
Labels: CS02

#419 Legacy Version
  csaf_2.0/json_schema/csaf_json_schema.json
  csaf_2.0/prose/csaf-v2-editor-draft.md
  notes/whats-new-csaf-v2.0-cn01.md
Labels: CS02

#418 Bind remediation
  csaf_2.0/prose/csaf-v2-editor-draft.md
  csaf_2.0/test/validator/data/mandatory/OASIS_CSAF_TC-CSAF_2_0-2021-6-1-29-01.json
Labels: CS02

#427 Realm and Resoure conversion
  csaf_2.0/prose/csaf-v2-editor-draft.md
  notes/whats-new-csaf-v2.0-cn01.md
Labels: bug, CS02

#428 Language conversion
  csaf_2.0/prose/csaf-v2-editor-draft.md
  notes/whats-new-csaf-v2.0-cn01.md
Labels: CS02

#432 List_on_CSAF_aggregator rules
  csaf_2.0/prose/csaf-v2-editor-draft.md
Labels: CS02

#433 Editorials section 2.1
  csaf_2.0/prose/csaf-v2-editor-draft.md
Labels: CS02

#437 One version system
  csaf_2.0/prose/csaf-v2-editor-draft.md
  csaf_2.0/test/validator/data/mandatory/OASIS_CSAF_TC-CSAF_2_0-2021-6-1-30-01.json
Labels: CS02

#430 Retrieving rules
  csaf_2.0/prose/csaf-v2-editor-draft.md
Labels: CS02

#442 Fix nits in scope prose and adapt convention
  csaf_2.0/prose/csaf-v2-editor-draft.md
Labels: editorial

#445 List signatures and hashes in ROLIE
  csaf_2.0/examples/ROLIE/example-01-feed-tlp-white.json
  csaf_2.0/prose/csaf-v2-editor-draft.md
Labels: CS02

#447 ROLIE categories
  csaf_2.0/prose/csaf-v2-editor-draft.md
Labels: CS02

#448 Prohibit trailing white spaces
  csaf_2.0/json_schema/csaf_json_schema.json
  csaf_2.0/prose/csaf-v2-editor-draft.md
Labels: CS02

#449 Spelling & Formatting & Other
  csaf_2.0/prose/csaf-v2-editor-draft.md
Labels: CS02

#451 Tracking ID
  csaf_2.0/prose/csaf-v2-editor-draft.md
  notes/whats-new-csaf-v2.0-cn01.md
Labels: CS02

#455 Formatting
  csaf_2.0/prose/csaf-v2-editor-draft.md
Labels: editorial, CS02

#456 Vulnerability definition
  csaf_2.0/prose/csaf-v2-editor-draft.md
Labels: CS02

#401 Added effective CS01 version from docs.oasis-open.org
  csaf_2.0/prose/csaf-v2-editor-draft.md
Labels: enhancement, documentation, csaf 2.0, editorial, oasis_tc_process, CS01, user-question

#458 Review comments
  csaf_2.0/prose/csaf-v2-editor-draft.md
Labels: editorial

#459 Editorial 2022 02 23
  csaf_2.0/prose/csaf-v2-editor-draft.md
Labels: editorial

#461 Editorial 2022 02 23
  csaf_2.0/prose/csaf-v2-editor-draft.md
  csaf_2.0/test/validator/data/mandatory/OASIS_CSAF_TC-CSAF_2_0-2021-6-1-29-01.json
Labels: editorial

#464 Model numbers
  csaf_2.0/prose/csaf-v2-editor-draft.md
Labels: editorial

#452 CSAF SBOM matching system
  csaf_2.0/prose/csaf-v2-editor-draft.md
Labels: tc-discussion-needed

#454 Version ranges
  csaf_2.0/json_schema/csaf_json_schema.json
  csaf_2.0/prose/csaf-v2-editor-draft.md
  csaf_2.0/test/validator/data/informative/OASIS_CSAF_TC-CSAF_2_0-2021-6-3-10-01.json
  csaf_2.0/test/validator/data/informative/OASIS_CSAF_TC-CSAF_2_0-2021-6-3-11-01.json
  csaf_2.0/test/validator/data/mandatory/OASIS_CSAF_TC-CSAF_2_0-2021-6-1-31-01.json
  csaf_2.0/test/validator/data/optional/OASIS_CSAF_TC-CSAF_2_0-2021-6-2-18-01.json
Labels: tc-discussion-needed

#463 Enhance category semantics
  csaf_2.0/json_schema/csaf_json_schema.json
  csaf_2.0/prose/csaf-v2-editor-draft.md
  csaf_2.0/test/validator/data/mandatory/OASIS_CSAF_TC-CSAF_2_0-2021-6-1-27-01-01.json
  csaf_2.0/test/validator/data/mandatory/OASIS_CSAF_TC-CSAF_2_0-2021-6-1-27-02-01.json
  csaf_2.0/test/validator/data/mandatory/OASIS_CSAF_TC-CSAF_2_0-2021-6-1-27-03-01.json
  csaf_2.0/test/validator/data/mandatory/OASIS_CSAF_TC-CSAF_2_0-2021-6-1-27-04-01.json
  csaf_2.0/test/validator/data/mandatory/OASIS_CSAF_TC-CSAF_2_0-2021-6-1-27-05-01.json
  csaf_2.0/test/validator/data/mandatory/OASIS_CSAF_TC-CSAF_2_0-2021-6-1-27-06-01.json
  csaf_2.0/test/validator/data/mandatory/OASIS_CSAF_TC-CSAF_2_0-2021-6-1-27-07-01.json
  csaf_2.0/test/validator/data/mandatory/OASIS_CSAF_TC-CSAF_2_0-2021-6-1-27-08-01.json
  csaf_2.0/test/validator/data/mandatory/OASIS_CSAF_TC-CSAF_2_0-2021-6-1-27-09-01.json
  csaf_2.0/test/validator/data/mandatory/OASIS_CSAF_TC-CSAF_2_0-2021-6-1-27-10-01.json
Labels: tc-discussion-needed

#460 VEX flags
  csaf_2.0/json_schema/csaf_json_schema.json
  csaf_2.0/prose/csaf-v2-editor-draft.md
  csaf_2.0/test/validator/data/mandatory/OASIS_CSAF_TC-CSAF_2_0-2021-6-1-32-01.json
  notes/whats-new-csaf-v2.0-cn01.md
Labels: tc-discussion-needed

#466 VEX flags test
  csaf_2.0/json_schema/csaf_json_schema.json
  csaf_2.0/prose/csaf-v2-editor-draft.md
  csaf_2.0/test/validator/data/mandatory/OASIS_CSAF_TC-CSAF_2_0-2021-6-1-33-01.json
Labels: bug, CS02

#467 Editorial
  csaf_2.0/test/validator/data/mandatory/OASIS_CSAF_TC-CSAF_2_0-2021-6-1-33-01.json
Labels: CS02
