Repository oasis-tcs/csaf, pull requests merged in 2023-02, with the labels that each got.

#603 Submission request to advance CSAF v2.0 to an International Standard
  csaf_2.0/submit/README.md
  csaf_2.0/submit/pdf/submission-request.pdf
Labels: email, oasis_tc_process

#609 Fix GitHub Actions
  .github/workflows/cpe.yml
  .github/workflows/filenames.yml
  .github/workflows/main.yml
  .github/workflows/mandatory-tests.yml
  .github/workflows/validator.yml
Labels: tool

#612 Update filename test
  .github/workflows/filenames.yml
  csaf_2.0/test/filenames/check.py
  csaf_2.0/test/filenames/run_tests.sh
Labels: tool

#613 Simplify test call per user set labels of paikalta
  csaf_2.0/test/filenames/run_tests.sh
Labels: tool

#605 Register link relations for hash and signature
  csaf_2.0/register/link-relations/hash.md
  csaf_2.0/register/link-relations/signature.md
Labels: csaf 2.0, oasis_tc_process
